### ISSUE TITLE
Limited time range in export timeseries from raster

### ISSUE THREAD

**Issue by lisannewapstra** [nens/lizard-client#1171] opened 2021-06-30 14:52 UTC
### **Topdesk 2106 0204 - RHDHV & Topdesk 2106 0206 gemeente Enkhuizen (SED)**

Today I received 2 tickets of users that got a 400 error while exporting the rain in a certain point in the portal.
These exports worked earlier.
Users are requesting the rain layer more often these days because of the heavy rain. 

**What the user does and sees (and how to reproduce)**
1.  open the portal via https://rhdhv.lizard.net/nl/map/topography,raster$730d667/point/6.937716,52.319235/@52.3193,6.9446,14/Jan,01,2020-Jan,01,2021#timeseries-rasters

2. go to exporteer (right top) --> export from raster --> start export
3. wait till the export is ready (you should see a number above your name) and click on it if it is
4. you should see "Task [uuid] failed with exit code 400"

![image](https://user-images.githubusercontent.com/33685743/123981120-610c2200-d9c2-11eb-9c35-ce7eaaf96111.png)

**What I see in Flower**
({'GET': {'async': False, 'format': 'csv', 'geom': 'POINT (6.937716 52.319235)', 'interactive': True, 'srs': 'EPSG:4326', 'start': '2019-12-31T23:00:00.000Z', 'stop': '2020-12-31T23:00:00.000Z'}, 'QUERY_STRING': 'async=false&format=csv&geom=POINT+(6.937716+52.319235)&interactive=true&srs=EPSG:4326&start=2019-12-31T23:00:00.000Z&stop=2020-12-31T23:00:00.000Z', 'HTTP_HOST': 'rhdhv.lizard.net', 'PATH_INFO': '/api/v3/rasters/730d667/data/', 'REQUEST_METHOD': 'GET', 'async_user': 'lisanne.wapstra'},)

(..)
: {"status":400,"code":23,"message":"Too many timesteps requested #400.23","detail":"105409 (max 4096)"}

**Requested solution**
This can be improved via the frontend or the backend. Preferably, I think should be able to export more than 2 weeks. 
If that is not possible, I would at least improve the error message or state the maximum export in the export menu. 

@joeriverheijden @lexvand  What do you think? This is a recent change, RHDHV was able to export a years worth of data earlier.

**Comment by joeriverheijden** [comment] 2021-07-05 10:19
@lexvand @byrman @arjanverkerk @daanvaningen 

I think this change was implemented some weeks ago. Is this a front-end or back-end issue? Do we support a longer export window when "async=true"?

I've heard more users raising a decrease in usability with regards to this change. 
Can we think of a solution to enable users to export a couple of years of data instead of a max of 4096?

**Comment by lexvand** [comment] 2021-07-06 14:39
FYI: The limit is based on 2 weeks divided by 5 minutes (= 4032; rounded up to a nice 2^12).

The issue originates from a change in the backend to fix memory errors (#4407). We have assessed the risks properly at that time. A couple of ways we could have done this better:
- Explain the limitation to users in export modal (frontend)
- Forward the task error (400) properly to the task result/inbox (backend)
- Implement error handling in client (frontend; requires the previous bullet)

@daanvaningen @arjanverkerk Can we distinguish between sync and async routes (for this type of requests)? And what can be done with proper task feedback (same goes for nens/lizard-nxt#5086)?

**Comment by daanvaningen** [comment] 2021-07-07 07:40
- We can distinguish sync and async routes, whether or not we can afford more timestemps/pixels is up to Arjan I think. I feel like exporting years of data will be difficult to combine with this limit we have set, as there is a good reason for this implementation.
- Only technical solution I can think of, which would allow users to export years of data with a timestep of 5 minutes without hitting the databse too hard, is putting them on a low resource queue. But which will make the export take a lot of time. Additionally we would need to provide some kind of feedback on their position in this queue, which is difficult.
- Proper feedback should be doable.

**Comment by joeriverheijden** [comment] 2021-07-12 12:09
@daanvaningen @arjanverkerk 

- Could a month of 5min timesteps data fit within that reasoning?

**Comment by lisannewapstra** [comment] 2021-07-15 08:15
I just made and gave the concerned users a python script to export the point rain for longer periods.  Please, do extent the time as far as you can and make it a note in the export menu.

**Comment by joeriverheijden** [comment] 2021-07-15 08:33
@arjanverkerk could you please shine your light on this issue urgently?

**Comment by daanvaningen** [comment] 2021-07-15 08:51
My proposal would be to let users export any range of data they want but split the request in the backend to reasonable chunks and gather the result. So a request for 1 year of data could be split into 12 request of 1 month or 26 requests of 2 weeks behind the scenes. We then gather these results and present them as 1 file / result. But I don't know if this is possible @arjanverkerk ?

**Comment by Derryrover** [comment] 2021-07-15 14:21
@daanvaningen 
> My proposal would be to let users export any range of data they want but split the request in the backend to reasonable chunks and gather the result. So a request for 1 year of data could be split into 12 request of 1 month or 26 requests of 2 weeks behind the scenes. We then gather these results and present them as 1 file / result. But I don't know if this is possible ?

I like the idea.
We could go even further and instead glue together the results on the client.
If we know in advance that we always going to retrieve timeseries in static chunks we might even cache those.
I see a lot of similarities here with the tiled approach that maps often use.

**Comment by joeriverheijden** [comment] 2021-07-16 06:59
@Derryrover i think glueing it on the client is nice for users that use the client. Users that use our API would also want to make use of this feature. So i think glueing it on the back-end is a solution that works for both type of users...? 

What do you guys think?

**Comment by daanvaningen** [comment] 2021-07-16 07:13
Agreed, my idea was to do the gathering of the results in the backend to provide this functionality to all users, not only those who use the client. If we want we can do something extra in the frontend, maybe some kind of progress tracking?

**Comment by arjanverkerk** [comment] 2021-07-16 12:02
There are two reasons for the timesteps limitation:
1. GDAL also configures a limit for the amount of timestamps in a reproject operation.
2. The performance of raster requests could become very bad for so many timesteps, and before the timesteps limitation was introduced we also had memory errors.

Solution to 1:
- Increase the limit

Solution to 2:
- Personally I think no one should need more than the current amount of timesteps for a sync request (dashboards, clients, etc.)
- Currently async has the same limit as sync. We could give async a slightly higher limit, but there is also the risk of memory errors, especially when using an endpoint like zonal. I don't like memory errors for sync requests.
- The best thing to do, and I agree with Daan on this, is to have an approach similar to the geotiff export (/data endpoint of rasters): A really different codepath for async where data is fetched in smaller portions and glued together in a downloadable result. I see it as in improvement of our service, and having limitations on the amount of data that can be requested is not a bug.

So we should making the limits clear to the customer into a prio, and decide if it is worth the effort to go for the optimal async implementation.

**Comment by lisannewapstra** [comment] 2021-07-20 12:28
As this issue also raises an error in the Regenrapportage, I set this issue as a bug. 

@joeriverheijden

**Comment by joeriverheijden** [comment] 2021-07-20 13:31
The impact of this issue is getting bigger and bigger. I'm really unhappy with the fact that we've implemented a solution without thinking about the impact for our users. From the perspective of the user we've taken away functionality that they relied on. 
I understand that from our point of view this makes Lizard more reliable. 

@arjanverkerk @daanvaningen can you please investigate with the highest priority if we can increase the limit of requested timesteps such that the RainReport works again? 

@lexvand

**Comment by arjanverkerk** [comment] 2021-07-21 10:36
@joeriverheijden What is wrong with the solution proposed here: https://app.zenhub.com/workspaces/team-lizard-5ef307a0fac67c0022166258/issues/nens/rain_report/43 ?

**Comment by lisannewapstra** [comment] 2021-07-23 09:47
Now also reported by WRIS Utrecht - Arjan van der Steen

**Comment by arjanverkerk** [comment] 2021-07-29 13:18
I just made a PR to increased the raster-limit-timestamps setting in Lizard to 10000. #5192 Further efforts to make bigger raster timeseries exports possible when async can be discussed here: #5193

**Comment by lexvand** [comment] 2021-08-04 12:30
Alright, leaves us with the question: What to do to inform the user in the client and/or assist the user to stay within the limits?

I see 2 options:

1. [Simple] Add a line of text to the export modal to inform the user that the maximum number of timesteps is 10,000.
2. [More complicated] Based on the interval of the selected raster layer and the selected period, calculate the number of timesteps and increase the window if it is above the limit. (E.g. 1 year of 5 minute interval data would be above the limit, by requesting hourly data with `window=3600000` it would remain within the limits.)

@joeriverheijden We should make a decision on this and that determines the estimate for this issue.

**Comment by joeriverheijden** [comment] 2021-08-04 13:07
Hmm. Interesting. 

2. That is a very user friendly way of solving this. However, this only works for temporal rasters that have an aggregated store. What would happen if such a store is not available e.g. for temporal rasters from our client Water Insight? 

Maybe a combination of 1 a bit of 2 is best? So the user selects a period. We compute the amount of timesteps that takes for that specific raster and return that to the users. If it's above 10.000 we warn the user. If not the user can go ahead. 

@Derryrover @arjanverkerk Let me know what you think.

**Comment by Derryrover** [comment] 2021-08-05 07:57
The decision if "a timeseries or rasters window is too big to be exported" is a decision made by the backend.
We should therefore implement this "business logic" in the backend.

I think backend can provide the information what exactly the available timesteps + windows are as part of a API response.
For example the following endpoint can contain a field "exportable_timesframes" that is a list of {"interval" + "maximum steps for that interval"}.
https://nxt3.staging.lizard.net/api/v4/rastersources/25cd4025-6053-4cc7-81f6-98654af626df/

Anyway that is the ideal situation I think.
For our current lizard-client we may already get into trouble implementing this.
We could investigate to export via other apps like catalogue and remove this whole feature from lizard-client.

**Comment by lexvand** [comment] 2021-08-10 14:24
As this is a temporal fix (we intend to improve the async task to have no more limit in the next release) we just go for option 1.

So, change the helptext from:
"You can select multiple raster-intersections to download. Once selected, press the "Start Export" button and the exporter will fetch the raster data behind the scenes. The exported data will be in CSV format."
to:
"Make your selection and press the "Start Export" button. The exporter will fetch the raster data behind the scenes and make it available for download through a message in your inbox. The format is CSV. **The export is limited to 10,000 timesteps (e.g. 1 month of 5 minute interval data).**"

**Comment by lisannewapstra** [comment] 2021-08-10 14:47
That sounds great.

**Comment by Derryrover** [comment] 2021-08-11 16:28
Deployed to staging as part of the landing page branch.
Not done on master.

**Comment by lexvand** [comment] 2021-08-13 07:47
Looks good!

**Closed** 2021-08-19 12:14 UTC
Labels: bug, Topdesk
