### ISSUE TITLE
Test new viewer url

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-client#1172] opened 2021-07-02 10:11 UTC
https://nxt3.staging.lizard.net/viewer

**Comment by Derryrover** [comment] 2021-07-02 10:12
@lexvand 
We can start testing the new url for lizard client on staging

**Comment by lexvand** [comment] 2021-07-13 14:00
Duplicate of nens/lizard-nxt#5012.

**Closed by lexvand** 2021-07-13 14:00 UTC
Labels: duplicate
