### ISSUE TITLE
Navigate back from lizard-client to Landing-page

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-client#1176] opened 2021-07-23 15:22 UTC
I think there is currently no way to do this.

- If the user was just coming from the landing page, then the user can use the browser 'back' button.
- One option would be to configure a "app" in the apps-menu to navigate to lizard.net
We could also always show this, so there is no need to configure for all users?
- We could also add another link at some place to navigate back.

**Comment by Derryrover** [comment] 2021-07-23 15:27
@Wolfensteijn 
@joeriverheijden 

Made this ticket to navigate from viewer back to landing page
Joeri, would adding the back button to the "apps" be acceptable? (see description).

**Comment by lexvand** [comment] 2021-08-09 16:11
Duplicate of #1177

**Closed by lexvand** 2021-08-09 16:11 UTC
Labels: duplicate
